---
- name: Destroy a Kind Cluster
  hosts: localhost
  connection: local
  tasks:

    - name: Check if Kind is installed
      command: kind version
      register: kind_version
      ignore_errors: true

    - name: Fail if Kind is not installed
      fail:
        msg: "Kind is not installed! Please install it first: https://kind.sigs.k8s.io/"
      when: kind_version.rc != 0

    - name: Check if kube-cluster01 exists
      command: kind get clusters
      register: existing_clusters
      changed_when: false

    - name: Destroy Kind Cluster if it matches rancher-cluster or kube-cluster01
      command: kind delete cluster --name "{{ item }}"
      when: item == 'rancher-cluster' or item == 'kube-cluster01'
      loop: "{{ existing_clusters.stdout_lines }}"

    - name: Verify Cluster Deletion
      command: kind get clusters
      register: clusters_after_deletion
      changed_when: false

    - name: Debug - Show remaining clusters
      debug:
        msg: "Remaining clusters: {{ clusters_after_deletion.stdout_lines }}"

