---
- name: Install monitoring_stack and expose it via Ingress
  hosts: localhost
  connection: local
  tasks:

    - name: Check if Kind is installed
      command: kind version
      register: kind_version
      ignore_errors: true

    - name: Fail if Kind is not installed
      fail:
        msg: "Kind is not installed! Please install it first."
      when: kind_version.rc != 0

    - name: Install monitoring_stack on cluster
      shell: "./bash/monitoring_stack.sh"
      register: monitoring_stack_install

    - name: Debug - Show monitoring_stack install
      debug:
        msg: "{{ monitoring_stack_install.stdout_lines }}"